version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30
        auth:
          username: tillhellmund
          password: $DOCKER_PASSWORD
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
                   -{{ checksum "core/build.gradle" }}
                   -{{ checksum "jodatime/build.gradle" }}
                   -{{ checksum "jsr310/build.gradle" }}
                   -{{ checksum "sample/build.gradle" }}
                   -{{ checksum "threetenabp/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}
                   -{{ checksum "core/build.gradle" }}
                   -{{ checksum "jodatime/build.gradle" }}
                   -{{ checksum "jsr310/build.gradle" }}
                   -{{ checksum "sample/build.gradle" }}
                   -{{ checksum "threetenabp/build.gradle" }}
      - run: 
          name: Run ktlintCheck
          command: ./gradlew --continue ktlintCheck
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
